// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// Medicine is the predicate function for medicine builders.
type Medicine func(*sql.Selector)

// Mmedicine is the predicate function for mmedicine builders.
type Mmedicine func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Prescription is the predicate function for prescription builders.
type Prescription func(*sql.Selector)

// Systemmember is the predicate function for systemmember builders.
type Systemmember func(*sql.Selector)
