// Code generated by entc, DO NOT EDIT.

package patient

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPatientName holds the string denoting the patient_name field in the database.
	FieldPatientName = "patient_name"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldPatientPhone holds the string denoting the patient_phone field in the database.
	FieldPatientPhone = "patient_phone"

	// EdgePrescriptions holds the string denoting the prescriptions edge name in mutations.
	EdgePrescriptions = "prescriptions"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// PrescriptionsTable is the table the holds the prescriptions relation/edge.
	PrescriptionsTable = "prescriptions"
	// PrescriptionsInverseTable is the table name for the Prescription entity.
	// It exists in this package in order to avoid circular dependency with the "prescription" package.
	PrescriptionsInverseTable = "prescriptions"
	// PrescriptionsColumn is the table column denoting the prescriptions relation/edge.
	PrescriptionsColumn = "Patient_ID"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldPatientName,
	FieldGender,
	FieldPatientPhone,
}

var (
	// PatientNameValidator is a validator for the "Patient_Name" field. It is called by the builders before save.
	PatientNameValidator func(string) error
	// PatientPhoneValidator is a validator for the "Patient_Phone" field. It is called by the builders before save.
	PatientPhoneValidator func(int) error
)
