// Code generated by entc, DO NOT EDIT.

package systemmember

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/jirayuSai/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// SystemmemberName applies equality check predicate on the "Systemmember_Name" field. It's identical to SystemmemberNameEQ.
func SystemmemberName(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSystemmemberName), v))
	})
}

// Password applies equality check predicate on the "Password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPassword), v))
	})
}

// SystemmemberNameEQ applies the EQ predicate on the "Systemmember_Name" field.
func SystemmemberNameEQ(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSystemmemberName), v))
	})
}

// SystemmemberNameNEQ applies the NEQ predicate on the "Systemmember_Name" field.
func SystemmemberNameNEQ(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSystemmemberName), v))
	})
}

// SystemmemberNameIn applies the In predicate on the "Systemmember_Name" field.
func SystemmemberNameIn(vs ...string) predicate.Systemmember {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Systemmember(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSystemmemberName), v...))
	})
}

// SystemmemberNameNotIn applies the NotIn predicate on the "Systemmember_Name" field.
func SystemmemberNameNotIn(vs ...string) predicate.Systemmember {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Systemmember(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSystemmemberName), v...))
	})
}

// SystemmemberNameGT applies the GT predicate on the "Systemmember_Name" field.
func SystemmemberNameGT(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSystemmemberName), v))
	})
}

// SystemmemberNameGTE applies the GTE predicate on the "Systemmember_Name" field.
func SystemmemberNameGTE(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSystemmemberName), v))
	})
}

// SystemmemberNameLT applies the LT predicate on the "Systemmember_Name" field.
func SystemmemberNameLT(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSystemmemberName), v))
	})
}

// SystemmemberNameLTE applies the LTE predicate on the "Systemmember_Name" field.
func SystemmemberNameLTE(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSystemmemberName), v))
	})
}

// SystemmemberNameContains applies the Contains predicate on the "Systemmember_Name" field.
func SystemmemberNameContains(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSystemmemberName), v))
	})
}

// SystemmemberNameHasPrefix applies the HasPrefix predicate on the "Systemmember_Name" field.
func SystemmemberNameHasPrefix(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSystemmemberName), v))
	})
}

// SystemmemberNameHasSuffix applies the HasSuffix predicate on the "Systemmember_Name" field.
func SystemmemberNameHasSuffix(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSystemmemberName), v))
	})
}

// SystemmemberNameEqualFold applies the EqualFold predicate on the "Systemmember_Name" field.
func SystemmemberNameEqualFold(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSystemmemberName), v))
	})
}

// SystemmemberNameContainsFold applies the ContainsFold predicate on the "Systemmember_Name" field.
func SystemmemberNameContainsFold(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSystemmemberName), v))
	})
}

// PasswordEQ applies the EQ predicate on the "Password" field.
func PasswordEQ(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPassword), v))
	})
}

// PasswordNEQ applies the NEQ predicate on the "Password" field.
func PasswordNEQ(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPassword), v))
	})
}

// PasswordIn applies the In predicate on the "Password" field.
func PasswordIn(vs ...string) predicate.Systemmember {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Systemmember(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPassword), v...))
	})
}

// PasswordNotIn applies the NotIn predicate on the "Password" field.
func PasswordNotIn(vs ...string) predicate.Systemmember {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Systemmember(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPassword), v...))
	})
}

// PasswordGT applies the GT predicate on the "Password" field.
func PasswordGT(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPassword), v))
	})
}

// PasswordGTE applies the GTE predicate on the "Password" field.
func PasswordGTE(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPassword), v))
	})
}

// PasswordLT applies the LT predicate on the "Password" field.
func PasswordLT(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPassword), v))
	})
}

// PasswordLTE applies the LTE predicate on the "Password" field.
func PasswordLTE(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPassword), v))
	})
}

// PasswordContains applies the Contains predicate on the "Password" field.
func PasswordContains(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPassword), v))
	})
}

// PasswordHasPrefix applies the HasPrefix predicate on the "Password" field.
func PasswordHasPrefix(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPassword), v))
	})
}

// PasswordHasSuffix applies the HasSuffix predicate on the "Password" field.
func PasswordHasSuffix(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPassword), v))
	})
}

// PasswordEqualFold applies the EqualFold predicate on the "Password" field.
func PasswordEqualFold(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPassword), v))
	})
}

// PasswordContainsFold applies the ContainsFold predicate on the "Password" field.
func PasswordContainsFold(v string) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPassword), v))
	})
}

// HasPrescriptions applies the HasEdge predicate on the "prescriptions" edge.
func HasPrescriptions() predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PrescriptionsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PrescriptionsTable, PrescriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrescriptionsWith applies the HasEdge predicate on the "prescriptions" edge with a given conditions (other predicates).
func HasPrescriptionsWith(preds ...predicate.Prescription) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PrescriptionsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PrescriptionsTable, PrescriptionsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Systemmember) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Systemmember) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Systemmember) predicate.Systemmember {
	return predicate.Systemmember(func(s *sql.Selector) {
		p(s.Not())
	})
}
