// Code generated by entc, DO NOT EDIT.

package mmedicine

const (
	// Label holds the string label denoting the mmedicine type in the database.
	Label = "mmedicine"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMmedicineName holds the string denoting the mmedicine_name field in the database.
	FieldMmedicineName = "mmedicine_name"

	// EdgePrescriptions holds the string denoting the prescriptions edge name in mutations.
	EdgePrescriptions = "prescriptions"

	// Table holds the table name of the mmedicine in the database.
	Table = "mmedicines"
	// PrescriptionsTable is the table the holds the prescriptions relation/edge.
	PrescriptionsTable = "prescriptions"
	// PrescriptionsInverseTable is the table name for the Prescription entity.
	// It exists in this package in order to avoid circular dependency with the "prescription" package.
	PrescriptionsInverseTable = "prescriptions"
	// PrescriptionsColumn is the table column denoting the prescriptions relation/edge.
	PrescriptionsColumn = "Mmedicine_ID"
)

// Columns holds all SQL columns for mmedicine fields.
var Columns = []string{
	FieldID,
	FieldMmedicineName,
}

var (
	// MmedicineNameValidator is a validator for the "Mmedicine_Name" field. It is called by the builders before save.
	MmedicineNameValidator func(string) error
)
