// Code generated by entc, DO NOT EDIT.

package mmedicine

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/jirayuSai/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// MmedicineName applies equality check predicate on the "Mmedicine_Name" field. It's identical to MmedicineNameEQ.
func MmedicineName(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameEQ applies the EQ predicate on the "Mmedicine_Name" field.
func MmedicineNameEQ(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameNEQ applies the NEQ predicate on the "Mmedicine_Name" field.
func MmedicineNameNEQ(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameIn applies the In predicate on the "Mmedicine_Name" field.
func MmedicineNameIn(vs ...string) predicate.Mmedicine {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Mmedicine(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldMmedicineName), v...))
	})
}

// MmedicineNameNotIn applies the NotIn predicate on the "Mmedicine_Name" field.
func MmedicineNameNotIn(vs ...string) predicate.Mmedicine {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Mmedicine(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldMmedicineName), v...))
	})
}

// MmedicineNameGT applies the GT predicate on the "Mmedicine_Name" field.
func MmedicineNameGT(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameGTE applies the GTE predicate on the "Mmedicine_Name" field.
func MmedicineNameGTE(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameLT applies the LT predicate on the "Mmedicine_Name" field.
func MmedicineNameLT(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameLTE applies the LTE predicate on the "Mmedicine_Name" field.
func MmedicineNameLTE(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameContains applies the Contains predicate on the "Mmedicine_Name" field.
func MmedicineNameContains(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameHasPrefix applies the HasPrefix predicate on the "Mmedicine_Name" field.
func MmedicineNameHasPrefix(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameHasSuffix applies the HasSuffix predicate on the "Mmedicine_Name" field.
func MmedicineNameHasSuffix(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameEqualFold applies the EqualFold predicate on the "Mmedicine_Name" field.
func MmedicineNameEqualFold(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldMmedicineName), v))
	})
}

// MmedicineNameContainsFold applies the ContainsFold predicate on the "Mmedicine_Name" field.
func MmedicineNameContainsFold(v string) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldMmedicineName), v))
	})
}

// HasPrescriptions applies the HasEdge predicate on the "prescriptions" edge.
func HasPrescriptions() predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PrescriptionsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PrescriptionsTable, PrescriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrescriptionsWith applies the HasEdge predicate on the "prescriptions" edge with a given conditions (other predicates).
func HasPrescriptionsWith(preds ...predicate.Prescription) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PrescriptionsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PrescriptionsTable, PrescriptionsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Mmedicine) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Mmedicine) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Mmedicine) predicate.Mmedicine {
	return predicate.Mmedicine(func(s *sql.Selector) {
		p(s.Not())
	})
}
