// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/jirayuSai/app/ent/mmedicine"
	"github.com/jirayuSai/app/ent/prescription"
)

// MmedicineCreate is the builder for creating a Mmedicine entity.
type MmedicineCreate struct {
	config
	mutation *MmedicineMutation
	hooks    []Hook
}

// SetMmedicineName sets the Mmedicine_Name field.
func (mc *MmedicineCreate) SetMmedicineName(s string) *MmedicineCreate {
	mc.mutation.SetMmedicineName(s)
	return mc
}

// AddPrescriptionIDs adds the prescriptions edge to Prescription by ids.
func (mc *MmedicineCreate) AddPrescriptionIDs(ids ...int) *MmedicineCreate {
	mc.mutation.AddPrescriptionIDs(ids...)
	return mc
}

// AddPrescriptions adds the prescriptions edges to Prescription.
func (mc *MmedicineCreate) AddPrescriptions(p ...*Prescription) *MmedicineCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return mc.AddPrescriptionIDs(ids...)
}

// Mutation returns the MmedicineMutation object of the builder.
func (mc *MmedicineCreate) Mutation() *MmedicineMutation {
	return mc.mutation
}

// Save creates the Mmedicine in the database.
func (mc *MmedicineCreate) Save(ctx context.Context) (*Mmedicine, error) {
	if _, ok := mc.mutation.MmedicineName(); !ok {
		return nil, &ValidationError{Name: "Mmedicine_Name", err: errors.New("ent: missing required field \"Mmedicine_Name\"")}
	}
	if v, ok := mc.mutation.MmedicineName(); ok {
		if err := mmedicine.MmedicineNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Mmedicine_Name", err: fmt.Errorf("ent: validator failed for field \"Mmedicine_Name\": %w", err)}
		}
	}
	var (
		err  error
		node *Mmedicine
	)
	if len(mc.hooks) == 0 {
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MmedicineMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mc.mutation = mutation
			node, err = mc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			mut = mc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MmedicineCreate) SaveX(ctx context.Context) *Mmedicine {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mc *MmedicineCreate) sqlSave(ctx context.Context) (*Mmedicine, error) {
	m, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	m.ID = int(id)
	return m, nil
}

func (mc *MmedicineCreate) createSpec() (*Mmedicine, *sqlgraph.CreateSpec) {
	var (
		m     = &Mmedicine{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: mmedicine.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mmedicine.FieldID,
			},
		}
	)
	if value, ok := mc.mutation.MmedicineName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: mmedicine.FieldMmedicineName,
		})
		m.MmedicineName = value
	}
	if nodes := mc.mutation.PrescriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mmedicine.PrescriptionsTable,
			Columns: []string{mmedicine.PrescriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prescription.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return m, _spec
}
