// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/jirayuSai/app/ent/doctor"
	"github.com/jirayuSai/app/ent/medicine"
	"github.com/jirayuSai/app/ent/patient"
	"github.com/jirayuSai/app/ent/prescription"
	"github.com/jirayuSai/app/ent/systemmember"
)

// PrescriptionCreate is the builder for creating a Prescription entity.
type PrescriptionCreate struct {
	config
	mutation *PrescriptionMutation
	hooks    []Hook
}

// SetDatetime sets the Datetime field.
func (pc *PrescriptionCreate) SetDatetime(t time.Time) *PrescriptionCreate {
	pc.mutation.SetDatetime(t)
	return pc
}

// SetPatientID sets the patient edge to Patient by id.
func (pc *PrescriptionCreate) SetPatientID(id int) *PrescriptionCreate {
	pc.mutation.SetPatientID(id)
	return pc
}

// SetNillablePatientID sets the patient edge to Patient by id if the given value is not nil.
func (pc *PrescriptionCreate) SetNillablePatientID(id *int) *PrescriptionCreate {
	if id != nil {
		pc = pc.SetPatientID(*id)
	}
	return pc
}

// SetPatient sets the patient edge to Patient.
func (pc *PrescriptionCreate) SetPatient(p *Patient) *PrescriptionCreate {
	return pc.SetPatientID(p.ID)
}

// SetDoctorID sets the doctor edge to Doctor by id.
func (pc *PrescriptionCreate) SetDoctorID(id int) *PrescriptionCreate {
	pc.mutation.SetDoctorID(id)
	return pc
}

// SetNillableDoctorID sets the doctor edge to Doctor by id if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableDoctorID(id *int) *PrescriptionCreate {
	if id != nil {
		pc = pc.SetDoctorID(*id)
	}
	return pc
}

// SetDoctor sets the doctor edge to Doctor.
func (pc *PrescriptionCreate) SetDoctor(d *Doctor) *PrescriptionCreate {
	return pc.SetDoctorID(d.ID)
}

// SetSystemmemberID sets the systemmember edge to Systemmember by id.
func (pc *PrescriptionCreate) SetSystemmemberID(id int) *PrescriptionCreate {
	pc.mutation.SetSystemmemberID(id)
	return pc
}

// SetNillableSystemmemberID sets the systemmember edge to Systemmember by id if the given value is not nil.
func (pc *PrescriptionCreate) SetNillableSystemmemberID(id *int) *PrescriptionCreate {
	if id != nil {
		pc = pc.SetSystemmemberID(*id)
	}
	return pc
}

// SetSystemmember sets the systemmember edge to Systemmember.
func (pc *PrescriptionCreate) SetSystemmember(s *Systemmember) *PrescriptionCreate {
	return pc.SetSystemmemberID(s.ID)
}

// AddMedicineIDs adds the medicines edge to Medicine by ids.
func (pc *PrescriptionCreate) AddMedicineIDs(ids ...int) *PrescriptionCreate {
	pc.mutation.AddMedicineIDs(ids...)
	return pc
}

// AddMedicines adds the medicines edges to Medicine.
func (pc *PrescriptionCreate) AddMedicines(m ...*Medicine) *PrescriptionCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return pc.AddMedicineIDs(ids...)
}

// Mutation returns the PrescriptionMutation object of the builder.
func (pc *PrescriptionCreate) Mutation() *PrescriptionMutation {
	return pc.mutation
}

// Save creates the Prescription in the database.
func (pc *PrescriptionCreate) Save(ctx context.Context) (*Prescription, error) {
	if _, ok := pc.mutation.Datetime(); !ok {
		return nil, &ValidationError{Name: "Datetime", err: errors.New("ent: missing required field \"Datetime\"")}
	}
	var (
		err  error
		node *Prescription
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PrescriptionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PrescriptionCreate) SaveX(ctx context.Context) *Prescription {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PrescriptionCreate) sqlSave(ctx context.Context) (*Prescription, error) {
	pr, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pr.ID = int(id)
	return pr, nil
}

func (pc *PrescriptionCreate) createSpec() (*Prescription, *sqlgraph.CreateSpec) {
	var (
		pr    = &Prescription{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: prescription.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: prescription.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Datetime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: prescription.FieldDatetime,
		})
		pr.Datetime = value
	}
	if nodes := pc.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prescription.PatientTable,
			Columns: []string{prescription.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prescription.DoctorTable,
			Columns: []string{prescription.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.SystemmemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prescription.SystemmemberTable,
			Columns: []string{prescription.SystemmemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemmember.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.MedicinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   prescription.MedicinesTable,
			Columns: prescription.MedicinesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicine.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pr, _spec
}
