// Code generated by entc, DO NOT EDIT.

package doctor

const (
	// Label holds the string label denoting the doctor type in the database.
	Label = "doctor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDoctorName holds the string denoting the doctor_name field in the database.
	FieldDoctorName = "doctor_name"
	// FieldDoctorEmail holds the string denoting the doctor_email field in the database.
	FieldDoctorEmail = "doctor_email"

	// EdgePrescriptions holds the string denoting the prescriptions edge name in mutations.
	EdgePrescriptions = "prescriptions"

	// Table holds the table name of the doctor in the database.
	Table = "doctors"
	// PrescriptionsTable is the table the holds the prescriptions relation/edge.
	PrescriptionsTable = "prescriptions"
	// PrescriptionsInverseTable is the table name for the Prescription entity.
	// It exists in this package in order to avoid circular dependency with the "prescription" package.
	PrescriptionsInverseTable = "prescriptions"
	// PrescriptionsColumn is the table column denoting the prescriptions relation/edge.
	PrescriptionsColumn = "Doctor_ID"
)

// Columns holds all SQL columns for doctor fields.
var Columns = []string{
	FieldID,
	FieldDoctorName,
	FieldDoctorEmail,
}

var (
	// DoctorNameValidator is a validator for the "Doctor_Name" field. It is called by the builders before save.
	DoctorNameValidator func(string) error
)
