// Code generated by entc, DO NOT EDIT.

package prescription

const (
	// Label holds the string label denoting the prescription type in the database.
	Label = "prescription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDatetime holds the string denoting the datetime field in the database.
	FieldDatetime = "datetime"

	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"
	// EdgeDoctor holds the string denoting the doctor edge name in mutations.
	EdgeDoctor = "doctor"
	// EdgeSystemmember holds the string denoting the systemmember edge name in mutations.
	EdgeSystemmember = "systemmember"
	// EdgeMedicines holds the string denoting the medicines edge name in mutations.
	EdgeMedicines = "medicines"

	// Table holds the table name of the prescription in the database.
	Table = "prescriptions"
	// PatientTable is the table the holds the patient relation/edge.
	PatientTable = "prescriptions"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "Patient_ID"
	// DoctorTable is the table the holds the doctor relation/edge.
	DoctorTable = "prescriptions"
	// DoctorInverseTable is the table name for the Doctor entity.
	// It exists in this package in order to avoid circular dependency with the "doctor" package.
	DoctorInverseTable = "doctors"
	// DoctorColumn is the table column denoting the doctor relation/edge.
	DoctorColumn = "Doctor_ID"
	// SystemmemberTable is the table the holds the systemmember relation/edge.
	SystemmemberTable = "prescriptions"
	// SystemmemberInverseTable is the table name for the Systemmember entity.
	// It exists in this package in order to avoid circular dependency with the "systemmember" package.
	SystemmemberInverseTable = "systemmembers"
	// SystemmemberColumn is the table column denoting the systemmember relation/edge.
	SystemmemberColumn = "Systemmember_ID"
	// MedicinesTable is the table the holds the medicines relation/edge. The primary key declared below.
	MedicinesTable = "prescription_medicines"
	// MedicinesInverseTable is the table name for the Medicine entity.
	// It exists in this package in order to avoid circular dependency with the "medicine" package.
	MedicinesInverseTable = "medicines"
)

// Columns holds all SQL columns for prescription fields.
var Columns = []string{
	FieldID,
	FieldDatetime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Prescription type.
var ForeignKeys = []string{
	"Doctor_ID",
	"Patient_ID",
	"Systemmember_ID",
}

var (
	// MedicinesPrimaryKey and MedicinesColumn2 are the table columns denoting the
	// primary key for the medicines relation (M2M).
	MedicinesPrimaryKey = []string{"prescription_id", "medicine_id"}
)
