/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPrescriptionEdges,
    EntPrescriptionEdgesFromJSON,
    EntPrescriptionEdgesFromJSONTyped,
    EntPrescriptionEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPrescription
 */
export interface EntPrescription {
    /**
     * Datetime holds the value of the "Datetime" field.
     * @type {string}
     * @memberof EntPrescription
     */
    datetime?: string;
    /**
     * 
     * @type {number}
     * @memberof EntPrescription
     */
    doctorID?: number;
    /**
     * 
     * @type {EntPrescriptionEdges}
     * @memberof EntPrescription
     */
    edges?: EntPrescriptionEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPrescription
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof EntPrescription
     */
    patientID?: number;
    /**
     * 
     * @type {number}
     * @memberof EntPrescription
     */
    systemmemberID?: number;
}

export function EntPrescriptionFromJSON(json: any): EntPrescription {
    return EntPrescriptionFromJSONTyped(json, false);
}

export function EntPrescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPrescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datetime': !exists(json, 'Datetime') ? undefined : json['Datetime'],
        'doctorID': !exists(json, 'doctor_ID') ? undefined : json['doctor_ID'],
        'edges': !exists(json, 'edges') ? undefined : EntPrescriptionEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'patientID': !exists(json, 'patient_ID') ? undefined : json['patient_ID'],
        'systemmemberID': !exists(json, 'systemmember_ID') ? undefined : json['systemmember_ID'],
    };
}

export function EntPrescriptionToJSON(value?: EntPrescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Datetime': value.datetime,
        'doctor_ID': value.doctorID,
        'edges': EntPrescriptionEdgesToJSON(value.edges),
        'id': value.id,
        'patient_ID': value.patientID,
        'systemmember_ID': value.systemmemberID,
    };
}


