/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntSystemmemberEdges,
    EntSystemmemberEdgesFromJSON,
    EntSystemmemberEdgesFromJSONTyped,
    EntSystemmemberEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSystemmember
 */
export interface EntSystemmember {
    /**
     * Password holds the value of the "Password" field.
     * @type {string}
     * @memberof EntSystemmember
     */
    password?: string;
    /**
     * SystemmemberName holds the value of the "Systemmember_Name" field.
     * @type {string}
     * @memberof EntSystemmember
     */
    systemmemberName?: string;
    /**
     * 
     * @type {EntSystemmemberEdges}
     * @memberof EntSystemmember
     */
    edges?: EntSystemmemberEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntSystemmember
     */
    id?: number;
}

export function EntSystemmemberFromJSON(json: any): EntSystemmember {
    return EntSystemmemberFromJSONTyped(json, false);
}

export function EntSystemmemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSystemmember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': !exists(json, 'Password') ? undefined : json['Password'],
        'systemmemberName': !exists(json, 'Systemmember_Name') ? undefined : json['Systemmember_Name'],
        'edges': !exists(json, 'edges') ? undefined : EntSystemmemberEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntSystemmemberToJSON(value?: EntSystemmember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Password': value.password,
        'Systemmember_Name': value.systemmemberName,
        'edges': EntSystemmemberEdgesToJSON(value.edges),
        'id': value.id,
    };
}


